"use client";

import { TeamResult } from "@/types";
import { TEAMS } from "@/lib/constants";
import { X, FileText, Target, Lightbulb, MessageSquare, Download } from "lucide-react";

interface FullResultsModalProps {
  result: TeamResult | null;
  onClose: () => void;
}

export default function FullResultsModal({ result, onClose }: FullResultsModalProps) {
  if (!result) return null;

  const team = TEAMS.find((t) => t.id === result.teamId);
  if (!team) return null;

  const handleDownload = () => {
    const content = `
${team.name} - Analysis Report
Generated: ${new Date(result.createdAt).toLocaleString()}

==== TRANSCRIPT ====
${result.transcript}

==== SUMMARY ====
${result.summary}

==== CONCLUSION ====
${result.conclusion}

==== CRITICAL ANALYSIS ====
${result.criticism}

---
Generated by OncoVoice AI - Clinical Discussion Intelligence
Powered by Cortex Innovative Solutions
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${team.name.replace(/\s+/g, "-")}-analysis-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4"
      onClick={onClose}
    >
      <div
        className="bg-slate-800 rounded-2xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-hidden flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div
          className="px-6 py-4 border-b border-slate-700 flex items-center justify-between"
          style={{ background: `linear-gradient(135deg, ${team.color}20 0%, ${team.color}05 100%)` }}
        >
          <div className="flex items-center gap-3">
            <div
              className={`w-12 h-12 rounded-full flex items-center justify-center ${team.bgColor} bg-opacity-20 border-2 ${team.borderColor}`}
            >
              <span className="text-xl font-bold" style={{ color: team.color }}>
                {team.id}
              </span>
            </div>
            <div>
              <h2 className="text-2xl font-bold text-white">{team.name} - Full Analysis</h2>
              <p className="text-sm text-slate-400">{new Date(result.createdAt).toLocaleString()}</p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 hover:bg-slate-700 rounded-lg transition-colors"
          >
            <X className="w-6 h-6 text-slate-400" />
          </button>
        </div>

        {/* Content - Scrollable */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {/* Transcript */}
          <section>
            <div className="flex items-center gap-2 mb-3">
              <MessageSquare className="w-5 h-5" style={{ color: team.color }} />
              <h3 className="text-xl font-semibold text-white">Transcript</h3>
            </div>
            <div className="bg-slate-900/50 rounded-lg p-4 border border-slate-700">
              <p className="text-slate-300 leading-relaxed whitespace-pre-wrap">{result.transcript}</p>
            </div>
          </section>

          {/* Summary */}
          <section>
            <div className="flex items-center gap-2 mb-3">
              <FileText className="w-5 h-5" style={{ color: team.color }} />
              <h3 className="text-xl font-semibold text-white">Summary</h3>
            </div>
            <div className="bg-slate-900/50 rounded-lg p-4 border border-slate-700">
              <p className="text-slate-300 leading-relaxed whitespace-pre-wrap">{result.summary}</p>
            </div>
          </section>

          {/* Conclusion */}
          <section>
            <div className="flex items-center gap-2 mb-3">
              <Target className="w-5 h-5" style={{ color: team.color }} />
              <h3 className="text-xl font-semibold text-white">Conclusion</h3>
            </div>
            <div className="bg-slate-900/50 rounded-lg p-4 border border-slate-700">
              <p className="text-slate-300 leading-relaxed whitespace-pre-wrap">{result.conclusion}</p>
            </div>
          </section>

          {/* Criticism */}
          <section>
            <div className="flex items-center gap-2 mb-3">
              <Lightbulb className="w-5 h-5" style={{ color: team.color }} />
              <h3 className="text-xl font-semibold text-white">Critical Analysis & Comparison</h3>
            </div>
            <div className="bg-slate-900/50 rounded-lg p-4 border border-slate-700">
              <p className="text-slate-300 leading-relaxed whitespace-pre-wrap">{result.criticism}</p>
            </div>
          </section>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-slate-700 flex items-center justify-between bg-slate-900/50">
          <button
            onClick={handleDownload}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg border-2 ${team.borderColor} ${team.hoverColor} bg-opacity-10 font-medium transition-all duration-300`}
            style={{ color: team.color }}
          >
            <Download className="w-4 h-4" />
            Download Report
          </button>

          <button
            onClick={onClose}
            className="px-6 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg font-medium text-white transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
